# NodeJS Version 16
FROM node:16.18-buster-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN pnpm install

# Set Env
ENV NODE_ENV production

# Cmd script
CMD ["pnpm", "run", "start"]
